// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkoHI4u3mCNxenqbNNDm_k9OC6qssBiPk',
    appId: '1:447694894462:web:4b5333a9f1b791ad556f2f',
    messagingSenderId: '447694894462',
    projectId: 'pet-feeder-b848f',
    authDomain: 'pet-feeder-b848f.firebaseapp.com',
    storageBucket: 'pet-feeder-b848f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKrxtIAYw1IiifMaA_qOBh7I7_VlksUw',
    appId: '1:447694894462:android:771fcf5f47c2c25f556f2f',
    messagingSenderId: '447694894462',
    projectId: 'pet-feeder-b848f',
    storageBucket: 'pet-feeder-b848f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD4VCN2V7TFrln9KNXqE8C9kqel8CgXPM',
    appId: '1:447694894462:ios:f791d3177d80912e556f2f',
    messagingSenderId: '447694894462',
    projectId: 'pet-feeder-b848f',
    storageBucket: 'pet-feeder-b848f.appspot.com',
    iosBundleId: 'com.example.petFeeder',
  );
}
