name: pet_feeder
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  calendar_view: ^1.0.4
  fl_chart: ^0.63.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  collection: ^1.17.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.1.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  accordion: ^2.6.0
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_ui_auth: ^1.9.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/main_logo.png
    - assets/images/dog_food/food_label.png
    - assets/images/dog_food/dog_food1.jpg
    - assets/images/dog_food/dog_food2.jpg
    - assets/images/dog_food/dog_food3.jpg
    - assets/images/user_pfp/user1.jpg
    - assets/images/user_pfp/user2.jpg
    - assets/images/user_pfp/user3.jpg
    - assets/images/bcs/bcs_cat_chart.png
    - assets/images/bcs/bcs_dog_chart.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico-Regular.ttf
