name: pet_feeder
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  calendar_view: ^1.0.4
  fl_chart: ^0.63.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  collection: ^1.17.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_form_builder: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/main_logo.png
    - assets/images/dog_food/food_label.png
    - assets/images/dog_food/dog_food1.jpg
    - assets/images/dog_food/dog_food2.jpg
    - assets/images/dog_food/dog_food3.jpg
    - assets/images/user_pfp/user1.jpg
    - assets/images/user_pfp/user2.jpg
    - assets/images/user_pfp/user3.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico-Regular.ttf
